---
- name: Provision and Configure Minecraft Server
  hosts: minecraft
  become: yes
  vars:
    minecraft_dir: /opt/minecraft
    minecraft_user: ec2-user
    server_jar_url: "https://piston-data.mojang.com/v1/objects/e6ec2f64e6080b9b5d9b471b291c33cc7f509733/server.jar"

  tasks:
    - name: Install dependencies
      package:
        name:
          - java-21-amazon-corretto
          - wget
        state: present

    - name: Create Minecraft directory
      file:
        path: "{{ minecraft_dir }}"
        state: directory
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_user }}"
        mode: '0755'

    - name: Download Minecraft server jar
      get_url:
        url: "{{ server_jar_url }}"
        dest: "{{ minecraft_dir }}/server.jar"
        mode: '0644'
        force: yes

    - name: Accept EULA
      copy:
        dest: "{{ minecraft_dir }}/eula.txt"
        content: "eula=true\n"
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_user }}"
        mode: '0644'

    - name: Create or update minecraft.service with proper shutdown handling
      copy:
        dest: /etc/systemd/system/minecraft.service
        owner: root
        group: root
        mode: '0644'
        content: |
          [Unit]
          Description=Minecraft Server
          After=network.target

          [Service]
          WorkingDirectory={{ minecraft_dir }}
          ExecStart=/usr/bin/java -Xmx1024M -Xms1024M -jar server.jar nogui
          ExecStop=/bin/kill -s SIGINT $MAINPID
          Restart=on-failure
          User={{ minecraft_user }}

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Enable and restart Minecraft service
      systemd:
        name: minecraft
        enabled: yes
        state: restarted

